trainer:
    name: ReplicationApartmentBlock
    min_steps: 64
    max_steps: 65
    visualize_output: false
    device_id: 0
    use_cuda: true
    num_hidden_channels: 12
    epochs: 20000
    batch_size: 5
    n_duplications: 3
    model_config:
        normal_std: 0.1
        update_net_channel_dims: [64, 64]
    optimizer_config:
        lr: 0.002
    dataset_config:
        nbt_path: structs_dataset/nbts/pixl_apartmentblock.nbt
        load_entity_config:
          padding: [[3,3], [3,3], [1,0]]
          block_priority: [179]

defaults:
    - replication